#ifndef CUTEHMI_APPFULL_SRC_VERSION_HPP
#define CUTEHMI_APPFULL_SRC_VERSION_HPP

//1 for development version, 0 for release
#define CUTYHMI_VERSION_IS_DEV 1
#define CUTYHMI_VERSION_MMM "0.0.0"
#define CUTYHMI_COPYRIGHT_YEAR "2015"

#ifndef NDEBUG
	#define CUTYHMI_VERSION_DEBUG_QUALIFIER ".debug"
#else
	#define CUTYHMI_VERSION_DEBUG_QUALIFIER ""
#endif

#if CUTYHMI_VERSION_IS_DEV == 1
	#define CUTYHMI_VERSION_DEV_QUALIFIER ".dev"
#else
	#define CUTYHMI_VERSION_DEV_QUALIFIER ""
#endif

#define CUTYHMI_VERSION CUTYHMI_VERSION_MMM CUTYHMI_VERSION_DEBUG_QUALIFIER CUTYHMI_VERSION_DEV_QUALIFIER

#endif

