#include <cutehmi/skeleton/logging.hpp>
#include <cutehmi/skeleton/metadata.hpp>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

Q_LOGGING_CATEGORY(cutehmi_skeleton_0_loggingCategory, CUTEHMI_SKELETON_NAME)
