#ifndef H_EXTENSIONS_CUTEHMI_WORKAROUNDS_QT5COMPATIBILITY_0_INCLUDE_CUTEHMI_WORKAROUNDS_QT5COMPATIBILITY_CUTEHMIQT6MOCINCLUDE_HPP
#define H_EXTENSIONS_CUTEHMI_WORKAROUNDS_QT5COMPATIBILITY_0_INCLUDE_CUTEHMI_WORKAROUNDS_QT5COMPATIBILITY_CUTEHMIQT6MOCINCLUDE_HPP

//<CuteHMI.Workarounds.Qt5Compatibility-5.workaround target="Qt" cause="Qt5">

#include <QObject>

#if (QT_VERSION < QT_VERSION_CHECK(6, 0, 0))
#define CUTEHMI_QT6_MOC_INCLUDE(...)
#else
#define CUTEHMI_QT6_MOC_INCLUDE Q_MOC_INCLUDE
#endif

//</CuteHMI.Workarounds.Qt5Compatibility-5.workaround>

#endif
