#include <cutehmi/workarounds/qt/labs/settings/logging.hpp>

#include <QtTest/QtTest>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace cutehmi {
namespace workarounds {
namespace qt {
namespace labs {
namespace settings {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(cutehmi::workarounds::qt::labs::settings::loggingCategory().categoryName(), "CuteHMI.Workarounds.Qt.labs.settings.1");
}

}
}
}
}
}

QTEST_MAIN(cutehmi::workarounds::qt::labs::settings::test_logging)
#include "test_logging.moc"
