#include <cutehmi/modfem/logging.hpp>

#include <QtTest/QtTest>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

namespace cutehmi {
namespace modfem {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(cutehmi::modfem::loggingCategory().categoryName(), "CuteHMI.ModFEM.0");
}

}
}

QTEST_MAIN(cutehmi::modfem::test_logging)
#include "test_logging.moc"
