#ifndef H_EXTENSIONS_CUTEHMI_SERVICES_2_INCLUDE_CUTEHMI_SERVICES_INTERNAL_PLATFORM_HPP
#define H_EXTENSIONS_CUTEHMI_SERVICES_2_INCLUDE_CUTEHMI_SERVICES_INTERNAL_PLATFORM_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include <QtGlobal>

#ifdef CUTEHMI_SERVICES_DYNAMIC
	#ifdef CUTEHMI_SERVICES_BUILD
		// Export symbols to dynamic library.
		#define CUTEHMI_SERVICES_API Q_DECL_EXPORT
		#ifdef CUTEHMI_SERVICES_TESTS
			// Export symbols to dynamic library.
			#define CUTEHMI_SERVICES_PRIVATE Q_DECL_EXPORT
		#else
			#define CUTEHMI_SERVICES_PRIVATE
		#endif
	#else
		// Using symbols from dynamic library.
		#define CUTEHMI_SERVICES_API Q_DECL_IMPORT
		#ifdef CUTEHMI_SERVICES_TESTS
			// Using symbols from dynamic library.
			#define CUTEHMI_SERVICES_PRIVATE Q_DECL_IMPORT
		#else
			#define CUTEHMI_SERVICES_PRIVATE
		#endif
	#endif
#else
	#define CUTEHMI_SERVICES_API
	#define CUTEHMI_SERVICES_PRIVATE
#endif

#endif

//(c)MP: Copyright © 2019, Michal Policht <michpolicht@gmail.com>. All rights reserved.
//(c)MP: This file is a part of CuteHMI.
//(c)MP: CuteHMI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
//(c)MP: CuteHMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
//(c)MP: You should have received a copy of the GNU Lesser General Public License along with CuteHMI.  If not, see <https://www.gnu.org/licenses/>.
