#ifndef H_MODULES_CUTEHMI__CHARTS__1_INCLUDE_CUTEHMI_CHARTS_METADATA_HPP
#define H_MODULES_CUTEHMI__CHARTS__1_INCLUDE_CUTEHMI_CHARTS_METADATA_HPP

#include "../../../cutehmi.metadata.hpp"

#endif // METADATA_HPP
