#include <cutehmi/services/logging.hpp>

#include <QtTest/QtTest>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

namespace cutehmi {
namespace services {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(cutehmi::services::loggingCategory().categoryName(), "CuteHMI.Services.2");
}

}
}

QTEST_MAIN(cutehmi::services::test_logging)
#include "test_logging.moc"
