#ifndef H_EXTENSIONS_TEMPLATES_CPPPLUGINSKELETON_0_INCLUDE_TEMPLATES_CPPPLUGINSKELETON_LOGGING_HPP
#define H_EXTENSIONS_TEMPLATES_CPPPLUGINSKELETON_0_INCLUDE_TEMPLATES_CPPPLUGINSKELETON_LOGGING_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "internal/platform.hpp"
#include <cutehmi/loggingMacros.hpp>

TEMPLATES_CPPPLUGINSKELETON_API Q_DECLARE_LOGGING_CATEGORY(templates_cpppluginskeleton_0_loggingCategory)

namespace templates {
namespace cpppluginskeleton {

inline
const QLoggingCategory & loggingCategory()
{
	return templates_cpppluginskeleton_0_loggingCategory();
}

}
}

#endif
