#include <templates/cpppluginskeleton/Init.hpp>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace templates {
namespace cpppluginskeleton {

Init::Init():
	::cutehmi::Initializer<Init>([]() {})
{
}

}
}
