#include <templates/cpppluginskeleton/logging.hpp>
#include <templates/cpppluginskeleton/metadata.hpp>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Q_LOGGING_CATEGORY(templates_cpppluginskeleton_0_loggingCategory, TEMPLATES_CPPPLUGINSKELETON_NAME)
