#include "logging.hpp"
#include "metadata.hpp"

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Q_LOGGING_CATEGORY(templates_cpppluginskeleton_loggingCategory, TEMPLATES_CPPPLUGINSKELETON_NAME)
