#ifndef H_MODULES_CUTEHMI__AUTHSSH__1_INCLUDE_CUTEHMI_AUTHSSH_METADATA_HPP
#define H_MODULES_CUTEHMI__AUTHSSH__1_INCLUDE_CUTEHMI_AUTHSSH_METADATA_HPP

#include "../../../cutehmi.metadata.hpp"

#endif // METADATA_HPP
