#ifndef H_EXTENSIONS_CUTEHMI_MODFEM_0_INCLUDE_CUTEHMI_MODFEM_LOGGING_HPP
#define H_EXTENSIONS_CUTEHMI_MODFEM_0_INCLUDE_CUTEHMI_MODFEM_LOGGING_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include "internal/platform.hpp"
#include <cutehmi/loggingMacros.hpp>

CUTEHMI_MODFEM_API Q_DECLARE_LOGGING_CATEGORY(cutehmi_modfem_0_loggingCategory)

namespace cutehmi {
namespace modfem {

inline
const QLoggingCategory & loggingCategory()
{
	return cutehmi_modfem_0_loggingCategory();
}

}
}

#endif
