#ifndef H_EXTENSIONS_CUTEHMI_MODFEM_0_INCLUDE_CUTEHMI_MODFEM_METADATA_HPP
#define H_EXTENSIONS_CUTEHMI_MODFEM_0_INCLUDE_CUTEHMI_MODFEM_METADATA_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include "../../../cutehmi.metadata.hpp"

#endif
