#ifndef H_MODULES_CUTEHMI__STUPID__1_INCLUDE_CUTEHMI_STUPID_METADATA_HPP
#define H_MODULES_CUTEHMI__STUPID__1_INCLUDE_CUTEHMI_STUPID_METADATA_HPP

#include "../../../cutehmi.metadata.hpp"

#endif // METADATA_HPP
