import qbs

import "Test.qbs" as Test

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Project {
	Test {
		testName: "test_logging"

		files: [
			"test_logging.cpp"
		]
	}
}
