#include <cutehmi/dataacquisition/logging.hpp>

#include <QtTest/QtTest>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace cutehmi {
namespace dataacquisition {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(cutehmi::dataacquisition::loggingCategory().categoryName(), "CuteHMI.DataAcquisition.0");
}

}
}

QTEST_MAIN(cutehmi::dataacquisition::test_logging)
#include "test_logging.moc"
