#include <cutehmi/shareddatabase/logging.hpp>
#include <cutehmi/shareddatabase/metadata.hpp>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Q_LOGGING_CATEGORY(cutehmi_shareddatabase_0_loggingCategory, CUTEHMI_SHAREDDATABASE_NAME)
