#ifndef H_EXTENSIONS_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_1_INCLUDE_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_LOGGING_HPP
#define H_EXTENSIONS_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_1_INCLUDE_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_LOGGING_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "internal/platform.hpp"
#include <cutehmi/loggingMacros.hpp>

CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_API Q_DECLARE_LOGGING_CATEGORY(cutehmi_workarounds_qt_labs_settings_loggingCategory)

namespace cutehmi {
namespace workarounds {
namespace qt {
namespace labs {
namespace settings {

inline
const QLoggingCategory & loggingCategory()
{
	CUTEHMI_LOGGING_CATEGORY_CHECK(cutehmi_workarounds_qt_labs_settings_loggingCategory());
	return cutehmi_workarounds_qt_labs_settings_loggingCategory();
}

}
}
}
}
}

#endif
