#ifndef H_EXTENSIONS_CUTEHMI_DATAACQUISITION_0_INCLUDE_CUTEHMI_DATAACQUISITION_LOGGING_HPP
#define H_EXTENSIONS_CUTEHMI_DATAACQUISITION_0_INCLUDE_CUTEHMI_DATAACQUISITION_LOGGING_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "internal/platform.hpp"
#include <cutehmi/loggingMacros.hpp>

CUTEHMI_DATAACQUISITION_API Q_DECLARE_LOGGING_CATEGORY(cutehmi_dataacquisition_0_loggingCategory)

namespace cutehmi {
namespace dataacquisition {

inline
const QLoggingCategory & loggingCategory()
{
	return cutehmi_dataacquisition_0_loggingCategory();
}

}
}

#endif
