#ifndef H_EXTENSIONS_CUTEHMI_DATAACQUISITION_0_SRC_CUTEHMI_DATAACQUISITION_INTERNAL_QMLPLUGIN_HPP
#define H_EXTENSIONS_CUTEHMI_DATAACQUISITION_0_SRC_CUTEHMI_DATAACQUISITION_INTERNAL_QMLPLUGIN_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include <QQmlExtensionPlugin>

namespace cutehmi {
namespace dataacquisition {
namespace internal {

/**
 * QML plugin.
 */
class QMLPlugin:
	public QQmlExtensionPlugin
{
		Q_OBJECT
		Q_PLUGIN_METADATA(IID QQmlExtensionInterface_iid)

	public:
		/**
		 * Register QML types.
		 * @param uri URI.
		 */
		void registerTypes(const char * uri) override;
};

}
}
}

#endif
