#include "QMLPlugin.hpp"

#include <cutehmi/dataacquisition/internal/common.hpp>
#include <cutehmi/dataacquisition/Schema.hpp>
//#include <cutehmi/dataacquisition/Tag.hpp>
#include <cutehmi/dataacquisition/TagValue.hpp>
#include <cutehmi/dataacquisition/HistoryWriter.hpp>
#include <cutehmi/dataacquisition/EventWriter.hpp>
#include <cutehmi/dataacquisition/RecencyWriter.hpp>

#include <QtQml>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace cutehmi {
namespace dataacquisition {
namespace internal {

void QMLPlugin::registerTypes(const char * uri)
{
	Q_ASSERT(uri == QLatin1String("CuteHMI.DataAcquisition"));

	qmlRegisterType<Schema>(uri, CUTEHMI_DATAACQUISITION_MAJOR, 0, "Schema");
	qmlRegisterType<TagValue>(uri, CUTEHMI_DATAACQUISITION_MAJOR, 0, "TagValue");
	qmlRegisterUncreatableType<AbstractWriter>(uri, CUTEHMI_DATAACQUISITION_MAJOR, 0, "AbstractWriter", "cutehmi::dataacquisition::AbstractWriter instance can not be created from QML.");
	qmlRegisterType<HistoryWriter>(uri, CUTEHMI_DATAACQUISITION_MAJOR, 0, "HistoryWriter");
	qmlRegisterType<RecencyWriter>(uri, CUTEHMI_DATAACQUISITION_MAJOR, 0, "RecencyWriter");
	qmlRegisterType<EventWriter>(uri, CUTEHMI_DATAACQUISITION_MAJOR, 0, "EventWriter");
}

}
}
}

//(c)C: Copyright © 2020, Michał Policht <michal@policht.pl>. All rights reserved.
//(c)C: This file is a part of CuteHMI.
//(c)C: CuteHMI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
//(c)C: CuteHMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
//(c)C: You should have received a copy of the GNU Lesser General Public License along with CuteHMI.  If not, see <https://www.gnu.org/licenses/>.
