#ifndef H_EXTENSIONS_CUTEHMI_SKELETON_0_INCLUDE_CUTEHMI_SKELETON_INTERNAL_PLATFORM_HPP
#define H_EXTENSIONS_CUTEHMI_SKELETON_0_INCLUDE_CUTEHMI_SKELETON_INTERNAL_PLATFORM_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include <QtGlobal>

#ifdef CUTEHMI_SKELETON_DYNAMIC
	#ifdef CUTEHMI_SKELETON_BUILD
		// Export symbols to dynamic library.
		#define CUTEHMI_SKELETON_API Q_DECL_EXPORT
		#ifdef CUTEHMI_SKELETON_TEST
			// Export symbols to dynamic library.
			#define CUTEHMI_SKELETON_PRIVATE Q_DECL_EXPORT
		#else
			#define CUTEHMI_SKELETON_PRIVATE
		#endif
	#else
		// Using symbols from dynamic library.
		#define CUTEHMI_SKELETON_API Q_DECL_IMPORT
		#ifdef CUTEHMI_SKELETON_TEST
			// Using symbols from dynamic library.
			#define CUTEHMI_SKELETON_PRIVATE Q_DECL_IMPORT
		#else
			#define CUTEHMI_SKELETON_PRIVATE
		#endif
	#endif
#else
	#define CUTEHMI_SKELETON_API
#endif

#endif
