#include <cutehmi/workarounds/qt/labs/settings/logging.hpp>
#include <cutehmi/workarounds/qt/labs/settings/metadata.hpp>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Q_LOGGING_CATEGORY(cutehmi_workarounds_qt_labs_settings_loggingCategory, CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_NAME)
