#ifndef MACROS_HPP
#define MACROS_HPP

#include "loggingMacros.hpp"

#ifdef Q_MOC_RUN
#define CUTEHMI_PRIVATE_SIGNALS_ACCESS_SPECIFIER Q_SIGNALS
#else
#define CUTEHMI_PRIVATE_SIGNALS_ACCESS_SPECIFIER private
#endif

#define CUTEHMI_PRIVATE_SIGNALS CUTEHMI_PRIVATE_SIGNALS_ACCESS_SPECIFIER

#ifdef Q_MOC_RUN
#define CUTEHMI_PROTECTED_SIGNALS_ACCESS_SPECIFIER Q_SIGNALS
#else
#define CUTEHMI_PROTECTED_SIGNALS_ACCESS_SPECIFIER protected
#endif

#define CUTEHMI_PROTECTED_SIGNALS CUTEHMI_PROTECTED_SIGNALS_ACCESS_SPECIFIER

#endif
