#include <cutehmi/dataacquisition/logging.hpp>
#include <cutehmi/dataacquisition/metadata.hpp>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Q_LOGGING_CATEGORY(cutehmi_dataacquisition_0_loggingCategory, CUTEHMI_DATAACQUISITION_NAME)
