#include "logging.hpp"
#include "metadata.hpp"

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Q_LOGGING_CATEGORY(templates_cppskeleton_loggingCategory, TEMPLATES_CPPSKELETON_NAME)
