import qbs

import cutehmi

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

cutehmi.Test {
	testedProduct: parent.parent.name

	Depends { name: product.testedProduct }
}
