#include <templates/cpppluginskeleton/autogen/logging.hpp>

#include <QtTest/QtTest>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace templates {
namespace cpppluginskeleton {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(templates::cpppluginskeleton::loggingCategory().categoryName(), "Templates.CppPluginSkeleton.0");
}

}
}

QTEST_MAIN(templates::cpppluginskeleton::test_logging)
#include "test_logging.moc"
