#include <cutehmi/modfem/logging.hpp>
#include <cutehmi/modfem/metadata.hpp>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

Q_LOGGING_CATEGORY(cutehmi_modfem_0_loggingCategory, CUTEHMI_MODFEM_NAME)
