#include <templates/cppskeleton/logging.hpp>

#include <QtTest/QtTest>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace templates {
namespace cppskeleton {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(templates::cppskeleton::loggingCategory().categoryName(), "Templates.CppSkeleton.0");
}

}
}

QTEST_MAIN(templates::cppskeleton::test_logging)
#include "test_logging.moc"
