#include "QMLPlugin.hpp" // IWYU pragma: keep

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace templates {
namespace cpppluginskeleton {
namespace internal {

void QMLPlugin::initializeEngine(QQmlEngine * engine, const char * uri)
{
	Q_UNUSED(uri)
	Q_UNUSED(engine)
}

}
}
}
