#ifndef H_EXTENSIONS_TEMPLATES_CPPPLUGINSKELETON_0_SRC_TEMPLATES_CPPPLUGINSKELETON_INTERNAL_QMLPLUGIN_HPP
#define H_EXTENSIONS_TEMPLATES_CPPPLUGINSKELETON_0_SRC_TEMPLATES_CPPPLUGINSKELETON_INTERNAL_QMLPLUGIN_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include <QQmlEngineExtensionPlugin>

namespace templates {
namespace cpppluginskeleton {
namespace internal {

/**
 * QML plugin.
 */
class QMLPlugin:
	public QQmlEngineExtensionPlugin
{
		Q_OBJECT
		Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

	public:
		void initializeEngine(QQmlEngine * engine, const char * uri) override;
};

}
}
}

#endif
