#include "QMLPlugin.hpp"

#include <templates/cpppluginskeleton/internal/common.hpp>

#include <QtQml>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace templates {
namespace cpppluginskeleton {
namespace internal {

void QMLPlugin::registerTypes(const char * uri)
{
	Q_ASSERT(uri == QLatin1String("Templates.CppPluginSkeleton"));

	qmlRegisterType<QObject>(uri, TEMPLATES_CPPPLUGINSKELETON_MAJOR, 0, "Object");
}

}
}
}
