#ifndef H_EXTENSIONS_TEMPLATES_CPPPLUGINSKELETON_0_SRC_TEMPLATES_CPPPLUGINSKELETON_INTERNAL_QMLPLUGIN_HPP
#define H_EXTENSIONS_TEMPLATES_CPPPLUGINSKELETON_0_SRC_TEMPLATES_CPPPLUGINSKELETON_INTERNAL_QMLPLUGIN_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include <QQmlExtensionPlugin>

namespace templates {
namespace cpppluginskeleton {
namespace internal {

/**
 * QML plugin.
 */
class QMLPlugin:
	public QQmlExtensionPlugin
{
		Q_OBJECT
		Q_PLUGIN_METADATA(IID QQmlExtensionInterface_iid)

	public:
		/**
		 * Register QML types.
		 * @param uri URI.
		 */
		void registerTypes(const char * uri) override;
};

}
}
}

#endif

//(c)ANYONE: Copyright © 2020, Anyone. All rights reserved.
//(c)ANYONE: This file is a part of CuteHMI.
//(c)ANYONE: CuteHMI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
//(c)ANYONE: CuteHMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
//(c)ANYONE: You should have received a copy of the GNU Lesser General Public License along with CuteHMI.  If not, see <https://www.gnu.org/licenses/>.
