#include <templates/skeleton/logging.hpp>

#include <QtTest/QtTest>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

namespace templates {
namespace skeleton {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(templates::skeleton::loggingCategory().categoryName(), "Templates.Skeleton.0");
}

}
}

QTEST_MAIN(templates::skeleton::test_logging)
#include "test_logging.moc"
