#ifndef H_EXTENSIONS_TEMPLATES_CPPSKELETON_0_INCLUDE_TEMPLATES_CPPSKELETON_EXCEPTION_HPP
#define H_EXTENSIONS_TEMPLATES_CPPSKELETON_0_INCLUDE_TEMPLATES_CPPSKELETON_EXCEPTION_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "internal/platform.hpp"

#include <cutehmi/ExceptionMixin.hpp>

namespace templates {
namespace cppskeleton {

class TEMPLATES_CPPSKELETON_API Exception:
	public ExceptionMixin<Exception>
{
		typedef ExceptionMixin<Exception> Parent;

	public:
		using Parent::Parent;
};

}
}

#endif
