#ifndef H_EXTENSIONS_TEMPLATES_CPPSKELETON_0_INCLUDE_TEMPLATES_CPPSKELETON_METADATA_HPP
#define H_EXTENSIONS_TEMPLATES_CPPSKELETON_0_INCLUDE_TEMPLATES_CPPSKELETON_METADATA_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "../../../cutehmi.metadata.hpp"

#endif
