#ifndef H_EXTENSIONS_CUTEHMI_SHAREDDATABASE_0_INCLUDE_CUTEHMI_SHAREDDATABASE_INTERNAL_PLATFORM_HPP
#define H_EXTENSIONS_CUTEHMI_SHAREDDATABASE_0_INCLUDE_CUTEHMI_SHAREDDATABASE_INTERNAL_PLATFORM_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include <QtGlobal>

#ifdef CUTEHMI_SHAREDDATABASE_DYNAMIC
	#ifdef CUTEHMI_SHAREDDATABASE_BUILD
		// Export symbols to dynamic library.
		#define CUTEHMI_SHAREDDATABASE_API Q_DECL_EXPORT
		#ifdef CUTEHMI_SHAREDDATABASE_TESTS
			// Export symbols to dynamic library.
			#define CUTEHMI_SHAREDDATABASE_PRIVATE Q_DECL_EXPORT
		#else
			#define CUTEHMI_SHAREDDATABASE_PRIVATE
		#endif
	#else
		// Using symbols from dynamic library.
		#define CUTEHMI_SHAREDDATABASE_API Q_DECL_IMPORT
		#ifdef CUTEHMI_SHAREDDATABASE_TESTS
			// Using symbols from dynamic library.
			#define CUTEHMI_SHAREDDATABASE_PRIVATE Q_DECL_IMPORT
		#else
			#define CUTEHMI_SHAREDDATABASE_PRIVATE
		#endif
	#endif
#else
	#define CUTEHMI_SHAREDDATABASE_API
	#define CUTEHMI_SHAREDDATABASE_PRIVATE
#endif

#endif
