#include "QMLPlugin.hpp"

#include <cutehmi/lockscreen/internal/common.hpp>
#include <cutehmi/lockscreen/Gatekeeper.hpp>

#include <QtQml>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

//<Doxygen-3.workaround target="Doxygen" cause="missing">
#ifdef DOXYGEN_WORKAROUND

namespace CuteHMI {

/**
 * Exposes cutehmi::lockscreen::Gatekeeper to QML.
 */
class Gatekeeper: public cutehmi::lockscreen::Gatekeeper {};

}

#endif
//</Doxygen-3.workaround>

namespace cutehmi {
namespace lockscreen {
namespace internal {

void QMLPlugin::registerTypes(const char * uri)
{
	Q_ASSERT(uri == QLatin1String("CuteHMI.LockScreen"));

	qmlRegisterType<cutehmi::lockscreen::Gatekeeper>(uri, CUTEHMI_MAJOR, 0, "Gatekeeper");
}

}
}
}
