#ifndef H_EXTENSIONS_CUTEHMI_LOCKSCREEN_1_INCLUDE_CUTEHMI_LOCKSCREEN_EXCEPTION_HPP
#define H_EXTENSIONS_CUTEHMI_LOCKSCREEN_1_INCLUDE_CUTEHMI_LOCKSCREEN_EXCEPTION_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "internal/platform.hpp"

#include <cutehmi/ExceptionMixin.hpp>

namespace cutehmi {
namespace lockscreen {

class CUTEHMI_LOCKSCREEN_API Exception:
	public ::cutehmi::ExceptionMixin<Exception>
{
		typedef ExceptionMixin<Exception> Parent;

	public:
		using Parent::Parent;
};

}
}

#endif
