#ifndef H_EXTENSIONS_CUTEHMI_LOCKSCREEN_2_INCLUDE_CUTEHMI_LOCKSCREEN_LOGGING_HPP
#define H_EXTENSIONS_CUTEHMI_LOCKSCREEN_2_INCLUDE_CUTEHMI_LOCKSCREEN_LOGGING_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "internal/platform.hpp"
#include <cutehmi/loggingMacros.hpp>

CUTEHMI_LOCKSCREEN_API Q_DECLARE_LOGGING_CATEGORY(cutehmi_lockscreen_loggingCategory)

namespace cutehmi {
namespace lockscreen {

inline
const QLoggingCategory & loggingCategory()
{
	CUTEHMI_LOGGING_CATEGORY_CHECK(cutehmi_lockscreen_loggingCategory());
	return cutehmi_lockscreen_loggingCategory();
}

}
}

#endif
