#ifndef H_EXTENSIONS_CUTEHMI_LOCKSCREEN_2_INCLUDE_CUTEHMI_LOCKSCREEN_METADATA_HPP
#define H_EXTENSIONS_CUTEHMI_LOCKSCREEN_2_INCLUDE_CUTEHMI_LOCKSCREEN_METADATA_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "../../../cutehmi.metadata.hpp"

#endif
