#ifndef H_MODULES_CUTEHMI__MODBUS__1_INCLUDE_CUTEHMI_MODBUS_METADATA_HPP
#define H_MODULES_CUTEHMI__MODBUS__1_INCLUDE_CUTEHMI_MODBUS_METADATA_HPP

#include "../../../cutehmi.metadata.hpp"

#endif // METADATA_HPP
