#include <cutehmi/lockscreen/logging.hpp>
#include <cutehmi/lockscreen/metadata.hpp>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

Q_LOGGING_CATEGORY(cutehmi_lockscreen_loggingCategory, CUTEHMI_LOCKSCREEN_NAME)
