#include <cutehmi/shareddatabase/logging.hpp>

#include <QtTest/QtTest>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace cutehmi {
namespace shareddatabase {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(cutehmi::shareddatabase::loggingCategory().categoryName(), "CuteHMI.SharedDatabase.0");
}

}
}

QTEST_MAIN(cutehmi::shareddatabase::test_logging)
#include "test_logging.moc"
