#include <templates/skeleton/logging.hpp>
#include <templates/skeleton/metadata.hpp>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

Q_LOGGING_CATEGORY(templates_skeleton_0_loggingCategory, TEMPLATES_SKELETON_NAME)
