#ifndef H_EXTENSIONS_CUTEHMI_LOCKSCREEN_2_INCLUDE_CUTEHMI_LOCKSCREEN_INTERNAL_PLATFORM_HPP
#define H_EXTENSIONS_CUTEHMI_LOCKSCREEN_2_INCLUDE_CUTEHMI_LOCKSCREEN_INTERNAL_PLATFORM_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include <QtGlobal>

#ifdef CUTEHMI_LOCKSCREEN_DYNAMIC
	#ifdef CUTEHMI_LOCKSCREEN_BUILD
		// Export symbols to dynamic library.
		#define CUTEHMI_LOCKSCREEN_API Q_DECL_EXPORT
		#ifdef CUTEHMI_LOCKSCREEN_TESTS
			// Export symbols to dynamic library.
			#define CUTEHMI_LOCKSCREEN_PRIVATE Q_DECL_EXPORT
		#else
			#define CUTEHMI_LOCKSCREEN_PRIVATE
		#endif
	#else
		// Using symbols from dynamic library.
		#define CUTEHMI_LOCKSCREEN_API Q_DECL_IMPORT
		#ifdef CUTEHMI_LOCKSCREEN_TESTS
			// Using symbols from dynamic library.
			#define CUTEHMI_LOCKSCREEN_PRIVATE Q_DECL_IMPORT
		#else
			#define CUTEHMI_LOCKSCREEN_PRIVATE
		#endif
	#endif
#else
	#define CUTEHMI_LOCKSCREEN_API
	#define CUTEHMI_LOCKSCREEN_PRIVATE
#endif

#endif
