#ifndef H_MODULES_TEMPLATES__MINIMAL__1_INCLUDE_TEMPLATES_MINIMAL_METADATA_HPP
#define H_MODULES_TEMPLATES__MINIMAL__1_INCLUDE_TEMPLATES_MINIMAL_METADATA_HPP

#include "../../../cutehmi.metadata.hpp"

#endif
