#ifndef H_EXTENSIONS_CUTEHMI_SERVICES_2_INCLUDE_CUTEHMI_SERVICES_LOGGING_HPP
#define H_EXTENSIONS_CUTEHMI_SERVICES_2_INCLUDE_CUTEHMI_SERVICES_LOGGING_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include "internal/platform.hpp"
#include <cutehmi/loggingMacros.hpp>

CUTEHMI_SERVICES_API Q_DECLARE_LOGGING_CATEGORY(cutehmi_services_2_loggingCategory)

namespace cutehmi {
namespace services {

inline
const QLoggingCategory & loggingCategory()
{
	return cutehmi_services_2_loggingCategory();
}

}
}

#endif
