#ifndef H_EXTENSIONS_CUTEHMI_SERVICES_2_INCLUDE_CUTEHMI_SERVICES_METADATA_HPP
#define H_EXTENSIONS_CUTEHMI_SERVICES_2_INCLUDE_CUTEHMI_SERVICES_METADATA_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include "../../../cutehmi.metadata.hpp"

#endif
