#ifndef H_EXTENSIONS_CUTEHMI_MODFEM_0_INCLUDE_CUTEHMI_MODFEM_INTERNAL_PLATFORM_HPP
#define H_EXTENSIONS_CUTEHMI_MODFEM_0_INCLUDE_CUTEHMI_MODFEM_INTERNAL_PLATFORM_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include <QtGlobal>

#ifdef CUTEHMI_MODFEM_DYNAMIC
	#ifdef CUTEHMI_MODFEM_BUILD
		// Export symbols to dynamic library.
		#define CUTEHMI_MODFEM_API Q_DECL_EXPORT
		#ifdef CUTEHMI_MODFEM_TESTS
			// Export symbols to dynamic library.
			#define CUTEHMI_MODFEM_PRIVATE Q_DECL_EXPORT
		#else
			#define CUTEHMI_MODFEM_PRIVATE
		#endif
	#else
		// Using symbols from dynamic library.
		#define CUTEHMI_MODFEM_API Q_DECL_IMPORT
		#ifdef CUTEHMI_MODFEM_TESTS
			// Using symbols from dynamic library.
			#define CUTEHMI_MODFEM_PRIVATE Q_DECL_IMPORT
		#else
			#define CUTEHMI_MODFEM_PRIVATE
		#endif
	#endif
#else
	#define CUTEHMI_MODFEM_API
	#define CUTEHMI_MODFEM_PRIVATE
#endif

#endif
