import qbs

import cutehmi

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

cutehmi.Test {
	testNamePrefix: parent.parent.name

	Depends { name: "CuteHMI.LockScreen.2" }
	Depends { name: "CuteHMI.Test.0" }
}
