#include <cutehmi/lockscreen/logging.hpp>

#include <QtTest/QtTest>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

namespace cutehmi {
namespace lockscreen {

class test_logging:
	public QObject
{
		Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(cutehmi::lockscreen::loggingCategory().categoryName(), "CuteHMI.LockScreen.2");
}

}
}

QTEST_MAIN(cutehmi::lockscreen::test_logging)
#include "test_logging.moc"
