#ifndef CUTEHMI_APPLITE_SRC_VERSION_HPP
#define CUTEHMI_APPLITE_SRC_VERSION_HPP

//1 for development version, 0 for release
#define CUTEHMI_VERSION_IS_DEV 1
#define CUTEHMI_VERSION_BRANCH "master"
#define CUTEHMI_APPLITE_COPYRIGHT_YEAR "2015-2016"

#ifndef NDEBUG
	#define CUTEHMI_VERSION_DEBUG_QUALIFIER ".debug"
#else
	#define CUTEHMI_VERSION_DEBUG_QUALIFIER ""
#endif

#if CUTEHMI_VERSION_IS_DEV == 1
	#define CUTEHMI_VERSION_DEV_QUALIFIER ".dev"
#else
	#define CUTEHMI_VERSION_DEV_QUALIFIER ""
#endif

#define CUTEHMI_APPLITE_VERSION CUTEHMI_VERSION_BRANCH CUTEHMI_VERSION_DEBUG_QUALIFIER CUTEHMI_VERSION_DEV_QUALIFIER

#endif
