#ifndef H_EXTENSIONS_TEMPLATES_SKELETON_0_INCLUDE_TEMPLATES_SKELETON_METADATA_HPP
#define H_EXTENSIONS_TEMPLATES_SKELETON_0_INCLUDE_TEMPLATES_SKELETON_METADATA_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include "../../../cutehmi.metadata.hpp"

#endif
