#ifndef H_EXTENSIONS_CUTEHMI_SKELETON_0_INCLUDE_CUTEHMI_SKELETON_LOGGING_HPP
#define H_EXTENSIONS_CUTEHMI_SKELETON_0_INCLUDE_CUTEHMI_SKELETON_LOGGING_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include "internal/platform.hpp"
#include <cutehmi/loggingMacros.hpp>

CUTEHMI_SKELETON_API Q_DECLARE_LOGGING_CATEGORY(cutehmi_skeleton_0_loggingCategory)

namespace cutehmi {
namespace skeleton {

inline
const QLoggingCategory & loggingCategory()
{
	return cutehmi_skeleton_0_loggingCategory();
}

}
}

#endif
