#ifndef H_MODULES_CUTEHMI__XML__1_INCLUDE_CUTEHMI_XML_METADATA_HPP
#define H_MODULES_CUTEHMI__XML__1_INCLUDE_CUTEHMI_XML_METADATA_HPP

#include "../../../cutehmi.metadata.hpp"

#endif // METADATA_HPP
