#ifndef H_EXTENSIONS_TEMPLATES_SKELETON_0_INCLUDE_TEMPLATES_SKELETON_INTERNAL_PLATFORM_HPP
#define H_EXTENSIONS_TEMPLATES_SKELETON_0_INCLUDE_TEMPLATES_SKELETON_INTERNAL_PLATFORM_HPP

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

#include <QtGlobal>

#ifdef TEMPLATES_SKELETON_DYNAMIC
	#ifdef TEMPLATES_SKELETON_BUILD
		// Export symbols to dynamic library.
		#define TEMPLATES_SKELETON_API Q_DECL_EXPORT
		#ifdef TEMPLATES_SKELETON_TEST
			// Export symbols to dynamic library.
			#define TEMPLATES_SKELETON_PRIVATE Q_DECL_EXPORT
		#else
			#define TEMPLATES_SKELETON_PRIVATE
		#endif
	#else
		// Using symbols from dynamic library.
		#define TEMPLATES_SKELETON_API Q_DECL_IMPORT
		#ifdef TEMPLATES_SKELETON_TEST
			// Using symbols from dynamic library.
			#define TEMPLATES_SKELETON_PRIVATE Q_DECL_IMPORT
		#else
			#define TEMPLATES_SKELETON_PRIVATE
		#endif
	#endif
#else
	#define TEMPLATES_SKELETON_API
#endif

#endif
