#ifndef H_EXTENSIONS_TEMPLATES_CPPSKELETON_0_INCLUDE_TEMPLATES_CPPSKELETON_INTERNAL_PLATFORM_HPP
#define H_EXTENSIONS_TEMPLATES_CPPSKELETON_0_INCLUDE_TEMPLATES_CPPSKELETON_INTERNAL_PLATFORM_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include <QtGlobal>

#ifdef TEMPLATES_CPPSKELETON_DYNAMIC
	#ifdef TEMPLATES_CPPSKELETON_BUILD
		// Export symbols to dynamic library.
		#define TEMPLATES_CPPSKELETON_API Q_DECL_EXPORT
		#ifdef TEMPLATES_CPPSKELETON_TESTS
			// Export symbols to dynamic library.
			#define TEMPLATES_CPPSKELETON_PRIVATE Q_DECL_EXPORT
		#else
			#define TEMPLATES_CPPSKELETON_PRIVATE
		#endif
	#else
		// Using symbols from dynamic library.
		#define TEMPLATES_CPPSKELETON_API Q_DECL_IMPORT
		#ifdef TEMPLATES_CPPSKELETON_TESTS
			// Using symbols from dynamic library.
			#define TEMPLATES_CPPSKELETON_PRIVATE Q_DECL_IMPORT
		#else
			#define TEMPLATES_CPPSKELETON_PRIVATE
		#endif
	#endif
#else
	#define TEMPLATES_CPPSKELETON_API
	#define TEMPLATES_CPPSKELETON_PRIVATE
#endif

#endif
