#include <cutehmi/services/logging.hpp>
#include <cutehmi/services/metadata.hpp>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

Q_LOGGING_CATEGORY(cutehmi_services_2_loggingCategory, CUTEHMI_SERVICES_NAME)
