#ifndef H_MODULES_CUTEHMI__SERVICES__1_INCLUDE_CUTEHMI_SERVICES_METADATA_HPP
#define H_MODULES_CUTEHMI__SERVICES__1_INCLUDE_CUTEHMI_SERVICES_METADATA_HPP

#include "../../../cutehmi.metadata.hpp"

#endif // METADATA_HPP
