#ifndef H_EXTENSIONS_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_1_INCLUDE_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_INTERNAL_COMMON_HPP
#define H_EXTENSIONS_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_1_INCLUDE_CUTEHMI_WORKAROUNDS_QT_LABS_SETTINGS_INTERNAL_COMMON_HPP

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

#include "platform.hpp"
#include "../metadata.hpp"


#include <QtGlobal>

#endif
