#include <cutehmi/skeleton/logging.hpp>

#include <QtTest/QtTest>

// This file has been autogenerated by 'ExtensionSkeleton.qbs'.

namespace cutehmi {
namespace skeleton {

class test_logging:
	public QObject
{
	Q_OBJECT

	private slots:
		void loggingCategory();
};

void test_logging::loggingCategory()
{
	QCOMPARE(cutehmi::skeleton::loggingCategory().categoryName(), "CuteHMI.Skeleton.0");
}

}
}

QTEST_MAIN(cutehmi::skeleton::test_logging)
#include "test_logging.moc"
