#ifndef CUTEHMI_LIBBASE_INCLUDE_BASE_INTERNAL_MACROS_HPP
#define CUTEHMI_LIBBASE_INCLUDE_BASE_INTERNAL_MACROS_HPP

#include "../macros.hpp"

Q_DECLARE_LOGGING_CATEGORY(cutehmi_base_loggingCategory)

#define CUTEHMI_BASE_QDEBUG(EXPR) CUTEHMI_BASE_QCDEBUG(cutehmi_base_loggingCategory, EXPR)
#define CUTEHMI_BASE_QINFO(EXPR) CUTEHMI_BASE_QCINFO(cutehmi_base_loggingCategory, EXPR)
#define CUTEHMI_BASE_QWARNING(EXPR) CUTEHMI_BASE_QCWARNING(cutehmi_base_loggingCategory, EXPR)
#define CUTEHMI_BASE_QCRITICAL(EXPR) CUTEHMI_BASE_QCCRITICAL(cutehmi_base_loggingCategory, EXPR)

#endif
