#include "QMLPlugin.hpp"

#include <cutehmi/shareddatabase/internal/common.hpp>
#include <cutehmi/shareddatabase/Database.hpp>

#include <QtQml>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

//<Doxygen-3.workaround target="Doxygen" cause="missing">
#ifdef DOXYGEN_WORKAROUND

namespace CuteHMI {
namespace SharedDatabase {

/**
 * Exposes cutehmi::shareddatabase::Database to QML.
 */
class Database: public cutehmi::shareddatabase::Database {};

}
}

#endif
//</Doxygen-3.workaround>

namespace cutehmi {
namespace shareddatabase {
namespace internal {

void QMLPlugin::registerTypes(const char * uri)
{
	Q_ASSERT(uri == QLatin1String("CuteHMI.SharedDatabase"));

	qmlRegisterType<Database>(uri, CUTEHMI_SHAREDDATABASE_MAJOR, 0, "Database");
}

}
}
}
