#include "QMLPlugin.hpp"

#include <cutehmi/shareddatabase/internal/common.hpp>
#include <cutehmi/shareddatabase/Database.hpp>

#include <QtQml>

// This file has been initially autogenerated by 'cutehmi.skeleton.cpp' Qbs module.

//<Doxygen-3.workaround target="Doxygen" cause="missing">
#ifdef DOXYGEN_WORKAROUND

namespace CuteHMI {
namespace SharedDatabase {

/**
 * Exposes cutehmi::shareddatabase::Database to QML.
 */
class Database: public cutehmi::shareddatabase::Database {};

}
}

#endif
//</Doxygen-3.workaround>

namespace cutehmi {
namespace shareddatabase {
namespace internal {

void QMLPlugin::registerTypes(const char * uri)
{
	Q_ASSERT(uri == QLatin1String("CuteHMI.SharedDatabase"));

	qmlRegisterType<Database>(uri, CUTEHMI_SHAREDDATABASE_MAJOR, 0, "Database");
}

}
}
}

//(c)C: Copyright © 2020, Michał Policht <michal@policht.pl>. All rights reserved.
//(c)C: This file is a part of CuteHMI.
//(c)C: CuteHMI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
//(c)C: CuteHMI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
//(c)C: You should have received a copy of the GNU Lesser General Public License along with CuteHMI.  If not, see <https://www.gnu.org/licenses/>.
